//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcceptApi.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcceptApi.Resourses.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This window has two parts: on the left hand-side, you can find a machine-translated text, which contains multiple sentences. Each of these sentences may be improved with your edits.&lt;/p&gt;&lt;p&gt;On the right hand-side, the “Current sentence to edit” box allows you to edit a machine-translated sentence, by following the guidelines that are made available to you via the “Guidelines” button. There are three buttons below the Edit box: an Undo button, a Redo button, and a spelling and grammar check button.&lt;/p&gt; &lt;p&gt;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostEditDialogContent {
            get {
                return ResourceManager.GetString("PostEditDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string PostEditDialogTitle {
            get {
                return ResourceManager.GetString("PostEditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save For Later.
        /// </summary>
        internal static string PostEditLabelCloseDialog {
            get {
                return ResourceManager.GetString("PostEditLabelCloseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on text to Edit:.
        /// </summary>
        internal static string PostEditLabelCreateTextToEdit {
            get {
                return ResourceManager.GetString("PostEditLabelCreateTextToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidelines.
        /// </summary>
        internal static string PostEditLabelGuideLines {
            get {
                return ResourceManager.GetString("PostEditLabelGuideLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string PostEditLabelHelp {
            get {
                return ResourceManager.GetString("PostEditLabelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Spelling, Grammar and Style.
        /// </summary>
        internal static string PostEditLabelPreEditTitle {
            get {
                return ResourceManager.GetString("PostEditLabelPreEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Task.
        /// </summary>
        internal static string PostEditLabelUserAllSelected {
            get {
                return ResourceManager.GetString("PostEditLabelUserAllSelected", resourceCulture);
            }
        }
    }
}
